version: '3'
services:
        web:
                image: flask_4444_v1
                build: .
                ports:
                        - "4444:4444"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
